name: test
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 8
    - uses: sbt/setup-sbt@v1
    - name: Test
      run: sbt test publishLocal
